apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: my-workflow-cbp-12202
on:
  workflow_dispatch:
jobs:
  checkout-combos:
    steps:
      - name: Both ID and Name
        id: checkout-both
        uses: cloudbees-io/checkout@v1

      - name: Name Only
        uses: cloudbees-io/checkout@v1

      - id: id-only-checkout
        uses: cloudbees-io/checkout@v1

      - uses: cloudbees-io/checkout@v1

      - uses: ./actions/cleanup-test

      - name: Hello World From Alpine
        uses: docker://alpine:3.21
        shell: sh
        run: |
          echo "Hello World"
